version: '3'
services:
  api:
    image: ghcr.io/yoyolick/api:latest
    ports:
      - 5505:5055
    volumes:
      - /home/dietpi/projects/hub/src/backend/backups:/src/backend/backups
    restart: unless-stopped
  gui:
    image: ghcr.io/yoyolick/hub:latest
    ports:
      - 3303:3000
    restart: unless-stopped
    depends_on:
      - api