name: stable build

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:./src/frontend"
          push: true
          tags: ghcr.io/yoyolick/hub:latest